RedHatQE/widgetastic.patternfly

src/widgetastic_patternfly/__init__.py

This needs for PR https://github.com/ManageIQ/integration_tests/pull/4146

Added all_options property into BootstrapSelect

---

src/widgetastic_patternfly/__init__.py
testing/test_buttons.py

```
In [1]: from widgetastic_patternfly import Button
In [2]: from utils import appliance
In [3]: ca = appliance.current_appliance
In [4]: b = Button(parent=ca.browser.widgetastic)
In [5]: b.click()
```

Button can now be generic

---

src/widgetastic_patternfly/__init__.py

fix for issue #https://github.com/ManageIQ/integration_tests/issues/4478

fix for Abandon Changes alert

---

src/widgetastic_patternfly/__init__.py

Made changes BootstrapTree to handle tag tree, this is needed for new tests and group conversion to widgetastic.

BootstrapTree update to handle tag tree

---

src/widgetastic_patternfly/__init__.py
testing/test_about_modal.py
testing/testing_page.html

In progress about modal and a test page for it

[RFR] Add about modal widget and test page

---

src/widgetastic_patternfly/__init__.py

This new widget encapsulates a Bootstrap nav component and provides methods for selecting an item and checking if an item is disabled.

Add a widget for the Bootstrap nav component

---

src/widgetastic_patternfly/__init__.py

Locator has been fixed, also `is_displayed` should be overridden.

Fix for BootstrapSwitch

---

src/widgetastic_patternfly/__init__.py

@psav @mshriver this should resolve the issues we are seeing.

Accordion: Fix header click and harden open

---

src/widgetastic_patternfly/__init__.py

This Save button is required for checking the disabled option of button on "Add page of timeprofile" in CFME.

Adding a new Button as required in CFME timeprofile page.

---

src/widgetastic_patternfly/__init__.py

I needed to be able to check if an item in a BootstrapNav existed. This method will look for an item that matches, and return true or false.

Add a has_item() method to see if a BootstrapNav has a particular item

---

src/widgetastic_patternfly/__init__.py

[RFR]Resolving Issue #29

---

src/widgetastic_patternfly/__init__.py

Locator update is needed for 5.9 test fix

BootsrtapSelector locator update for tags

---

src/widgetastic_patternfly/__init__.py

```python
/home/mshriver/repos/integration_tests/.cfme_tests/bin/python /usr/local/bin/pycharm-community-2017.2.2/helpers/pydev/pydevconsole.py 44831 44481
Python 2.7.14 (default, Nov  3 2017, 10:55:25) 
Type "copyright", "credits" or "license" for more information.
from cfme.utils import conf
from fixtures.pytest_store import store
from cfme.utils.appliance.implementations.ui import navigate_to
from cfme.utils import providers
Python 2.7.14 (default, Nov  3 2017, 10:55:25) 
<warnings skipped>
In[2]: ec2 = providers.get_crud('ec2west')
<warnings skipped>
In[3]: view = navigate_to(ec2, 'Details')
<warnings skipped>
In[4]: view.toolbar.configuration.item_select('Refresh Relationships and Power States', handle_alert=True)
In[5]: view.flash.assert_message('Refresh Provider initiated for 1 …
```

[RFR] Fix flash.assert_message_contains

---

src/widgetastic_patternfly/__init__.py

Fixed partial matching in BootstrapSelect

---

src/widgetastic_patternfly/__init__.py

Updating the logging for BootstrapSelect so that when a NoSuchElement exception occurs, a 'SelectItemNotFound' exception is raised.
The new exception logs the item targeted for selection, the widget repr, and a list of items in the select.
The goal is to aid in debugging when widget selection fails.

[RFR] Add exception logging to BootstrapSelect with new exception

---

src/widgetastic_patternfly/__init__.py

Added text partial match for sidebar navigation, as most of them, have some item count as random

Add text partial match for sidebar navigation

---

src/widgetastic_patternfly/__init__.py

unittest still missing, suggestions welcome

use six.string_types instead of basestring, addresses  #59

---

src/widgetastic_patternfly/__init__.py

copypasta from ManageIQ/integration_tests/widgetastic_manageiq

[RFR] Add breadcrumb widget

---

src/widgetastic_patternfly/__init__.py
testing/test_date_picker.py
testing/testing_page.html

Purpose or Intent
=================
- DatePicker widget for selection of date for read-only and read-write date box.
- Supporting `fill` as default method

DatePicker Widget

---

src/widgetastic_patternfly/__init__.py

Reverts RedHatQE/widgetastic.patternfly#61

Revert "Added the ability to access the nav_click in WT"

---

src/widgetastic_patternfly/__init__.py

where it doesn't scroll to hidden element

[RFR][1LP] fixing dropdown in 5.10 in FF60+ 

---

src/widgetastic_patternfly/__init__.py

Add a reason to the disabled item handling

Add a reason to the disabled item handling

---

src/widgetastic_patternfly/__init__.py

current flash widget cannot handle cases when each message is stored in its own flash_text_div. this fix should sort out this issue

[RFR] fix flash messages in hammer

---

testing/test_about_modal.py
testing/testing_page.html

1. Added respective `wait_for`
2. `h2` is title tag :)
Optional:
we can go with wait check in `widget` it self but I though better user decide in tests about this.

Fix about modal test

---

src/widgetastic_patternfly/__init__.py
testing/test_dropdowns.py
testing/testing_page.html

- Moving kebab widget from [miq](https://github.com/ManageIQ/integration_tests/blob/master/cfme/dashboard.py#L23)
- Changes:
- Added `locator` as on of optional agrument. So if id not match and want to select `kebab` other than first. 
- As its `dropdown` type  of  widget so methods should  similar to dropdown. renamed `select` method with `item_select`.
- Added `has_item` method
- Added test

[RFR] Kebab  Widget

---

src/widgetastic_patternfly/__init__.py

Adding a widget for a basic list-view handling class: 
https://www.patternfly.org/pattern-library/content-views/list-view/
This widget is designed to work similarly to `Table` and `TableRow`, except here we have `ItemsList` and `item_class` which is input as a parameter when the list is instantiated. The functionality and filtering is fairly bare-bones at this stage.

[RFR] Add in a widget for a list-view object

---

src/widgetastic_patternfly/__init__.py

Adding icons whose classes start with "pficon-" to `image_getter` in `BootstrapTreeview`

[RFR] Add in pficon to image_getter

---

src/widgetastic_patternfly/__init__.py
testing/test_buttons.py

Implementing fill method for `Button`.

[RFR] Add fill method for button

---

.travis.yml
setup.py
src/widgetastic_patternfly/__init__.py
tox.ini

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

[RFR] re pattern changes

---

src/widgetastic_patternfly/__init__.py

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

[RFR] hover property for dropdown

---

src/widgetastic_patternfly/__init__.py
testing/test_bootstrap_nav.py
testing/testing_page.html

Adding all options property for BoostrapNav

[RFR]Updating boostrap nav to include all_options

---

src/widgetastic_patternfly/__init__.py
testing/test_buttons.py
testing/testing_page.html

[1LP][RFR] Add Button.text and Button.read()

---

src/widgetastic_patternfly/__init__.py

Update the locator for NavDropdown, #98 was merged a bit early

[RFR] Add to the NavDropdown locator

---

testing/test_about_modal.py

Test is flaky, timing out waiting for modal to open on travis.

Update about modal test, longer timeout on modal opening

---

src/widgetastic_patternfly/__init__.py

[RFR] Add anyway as named kwarg

---

.travis.yml
setup.py
tox.ini

#108 included an f-string, but we still have 3.5 in the support matrix. Drop 3.5, support 3.6 and 3.7

[RFR] Update to py3.7 support only

---

src/widgetastic_patternfly/__init__.py
testing/testing_page.html

When scope is not defined, out of scope elements matching the text (not the expected element) gets selected, defining the scope helps select the correct element.

[WIP]Add scope to BootstrapNav methods

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
setup.cfg
setup.py

Move setuptools config into setup.cfg
Set minimum python version
https://github.com/RedHatQE/widgetastic.core/pull/214
https://github.com/RedHatQE/widgetastic.patternfly4/pull/129
Happening in wt.core and wt.pf4 as well

Move to py3.8 minimum
