src/widgetastic_patternfly/__init__.py

Behavior of `BootstrapSwitch` differs from usual `Checkbox`, so it should be inherited from `BaseInput`. This PR is changing the element which should be clicked and adding `text` property to get a text description.

BootstrapSwitch enhanced

---

src/widgetastic_patternfly/__init__.py
testing/test_buttons.py
testing/testing_page.html

Tested locally, the new tests fail before the change to moving `kwargs.pop('classes')` up in __init__.
Core failure was that when text is not supplied, the generator at L101/102 would pull kwargs[classes] and try to parse it into locator conditions as with the other attributes.  This fails because classes is not a standard button element attribute, and is handled in a separate block (passed as a list, not a string).
This was found during testing of MIQ pages where there is a dynamic table, and potentially multiple 'Add' buttons.  Defining a button with a mix of classes and attributes, with no text, produces an exception when the string formatting tries to call String.replace() on a list (classes).
* The about modal test failed, that's expected. 
* The button test, with new widget and …

[RFR] Fix button classes

---

src/widgetastic_patternfly/__init__.py

It seems this is patternfly or manageiq bug. 
For example there is BootstrapSwitch on Middleware->Servers->Add Deployment page, it is in "on" state by default but selenium's is_selected method will return False until it gets clicked.
The issue can be noticed in JS as well.
el = document.getElementById('force_deployment_cb')
el.checked (returns False though it is True)
This PR is a workaround for above issue.
Found by @hhovsepy

[RFR] BootstrapSwitch incorrect gets switch state in some cases

---

src/widgetastic_patternfly/__init__.py

Tested locally (pip-installed the branch and rerun the test); works.

Fix bootstrap switch to work as widget in tables

---

src/widgetastic_patternfly/__init__.py

The mouse movements are not required it seems, simplification solves the issue.
Minor speedup.

Fix VerticalNavigation

---

src/widgetastic_patternfly/__init__.py

Upstream has changed BootstrapTreeview. Now it has `miq-tree-view` in the root. Tested on CFME 5.7, 5.8 and upstream.

Fixed BootstrapTreeview for CFME 5.9

---

src/widgetastic_patternfly/__init__.py

I needed a way to check if a path exists in a tree view, so I added this method to contain the boilerplate code in a single place.

Add a has_path() method to the BootstrapTreeview

---

src/widgetastic_patternfly/__init__.py

Faced with strange behaviour for some of tags assignment pages, Dropdown HTML tree is different for 5.9 views. Dropdown button remains the same but the opened dropdown is under another div then button. Added small workaround to cover such case

5.9 workaround for dropdown

---

src/widgetastic_patternfly/__init__.py

Removing the ROOT also removed the is_displayed functionality.

Fix Tab.is_displayed

---

src/widgetastic_patternfly/__init__.py

In `assert_no_error()` method, flash message type `warning` should not count as error.
for more clarification adding one example[0]
[0] http://pastebin.test.redhat.com/575839

[RFR]warning should not count as error

---

src/widgetastic_patternfly/__init__.py

* To aid in the support of FF60, we need to tell WT when we think a
navigation will be occurring. This is done with the addition of the
nav_click parameter to the item_select on the Dropdown menu. It could
be in the future that more of these are needed on other items that do
navigations, such as the main navigation. I would prefer not to
blanket all clicks with it, as this will slow down testing.

Added the ability to access the nav_click in WT

---

src/widgetastic_patternfly/__init__.py

I encountered this HTML for a button:
```<button disabled type="button" class="btn btn-primary">Save</button>```
which evaluates to: 
```<button type="button" class="btn btn-primary" disabled="">Save</button>```
In this situation, `self.browser.get_attribute('disabled', self)` results in `'true'` when disabled and `'false'` when enabled. The current code does not detect this and always marks it as false (enabled). This is to resolve that condition.
As an addition, setting `== 'disabled'` looks strange if the function outputs true or false (not Pythonic `True` or `False`, just strings). Is that supposed to be that way? If not, I can modify my commit to remove that condition.

Added another condition encountered when working with buttons

---

.travis.yml
src/widgetastic_patternfly/__init__.py
src/widgetastic_patternfly/utils.py
testing/conftest.py
testing/test_agg_status_card.py
testing/testing_page.html
tox.ini

Adding widgets for Aggregate Status cards, per patternfly reference markup.
Making the locators modular, so that modifying them in application-specific widgets is easier.

[RFR] Add AggregateStatusCard widget and tests

---

src/widgetastic_patternfly/__init__.py

-  I observed that for `Dropdown` widget; we need method which will return `currently selected option`.
-  This type  of method is in `SelectedDropdown`. So change name of this method and moved to `Dropdown` class.
- Method name should be same for similar operation among all widgets. 
- We had used this in `SSUIDropdown`[0]. Now,  I need this for `custom button`. For checking the display option of `Group`. Objective is just check name display or not.
[0] https://github.com/ManageIQ/integration_tests/blob/master/widgetastic_manageiq/__init__.py#L1143

[1LP][RFR] read method to Dropdown

---

src/widgetastic_patternfly/__init__.py
testing/test_bootstrap_tree.py
testing/testing_page.html

The `BootstrapTreeview` widget currently has no support for trees which have more than one root. I propose that: 
1) We add a `root_items` property for this widget
2) Add a basic unit test for this widget.

[RFR] Add unit test for BootstrapTreeview widget, and root_items property

---

src/widgetastic_patternfly/__init__.py
testing/test_data_visualization.py
testing/testing_page.html

Part of https://github.com/RedHatQE/widgetastic.patternfly/issues/67
Adding fallowing `widgets` with `unit  test`:
```
1. Sparkline
2. Line Chart
a. single line
b. line chart
c. single spline chart
d. spline chart
3. Bar Chart
a. Vertical Bar Chart
a. Grouped Vertical Bar chart
b. Stacked Vertical Bar Chart
c. Horizontal Bar Chart
d. Grouped Horizontal Bar Chart
e. Stacked Horizontal Bar Chart
```

Charts:  Line, Bar, Spiral widgets

---

testing/test_dropdowns.py

Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>
No need to check open. After selection as per testing widget drawer close.
https://www.patternfly.org/pattern-library/widgets/#kebabs

Fix kebab test

---

src/widgetastic_patternfly/__init__.py

Noticed that sometimes, when you try to click the `location` web driver element that nothing happens. Clicking the actual link appears to resolve this issue without breaking current implementation.

[RFR] Click link, ".//a" in breadcrumb rather than ".//li" for click_location

---

src/widgetastic_patternfly/__init__.py
testing/test_modal.py
testing/testing_page.html

Adding a modal widget and a unit test to accompany it: 
https://www.patternfly.org/pattern-library/widgets/#modal
Since the form that is present in the modal can be general, the unit test provides an example use case for dealing with this. The `SpecificModal` inherits the `Modal` class and then overwrites the `body` widget.

[RFR]: Add in modal widget with basic functionality

---

src/widgetastic_patternfly/__init__.py

Changes:
1. Add a new `EXPAND_LOCATOR` to fix NavDropdown, which doesn't work when the dropdown element does not have a caret.

Add EXPAND_LOCATOR 

---

src/widgetastic_patternfly/__init__.py

Make the locators actually look at `li` classes, not just presence of a caret for NavDropdown expandable checks.
Use ParametrizedLocator, default the locator to wt.pf reference for NavDropdowns.

[RFR] Update NavDropdown locators

---

src/widgetastic_patternfly/__init__.py
src/widgetastic_patternfly/utils.py
testing/test_about_modal.py

title locators changed in CFME, allow h1 or h2 by default
change title and trademark to not use Text widgets
Updated title/trade_mark properties to just find/read the elements directly
Change root locator, make id optional, use it when available.

update AboutModal, change locators

---

src/widgetastic_patternfly/__init__.py

**Changes:**
1. Remove `is_displayed` from `AboutModal` and use the parent is_displayed instead.
2. Wrap `is_open` code within a try and catch block because if the modal is not opened `is_open` raises `NoSuchElementException`.

[1LP][RFR] Fix is_displayed for about modal

---

src/widgetastic_patternfly/__init__.py
testing/test_bootstrap_nav.py
testing/testing_page.html

- Add the ability to pass a partial_match text to BootstrapNav's is_disabled.
Require this change for integration_tests [PR#9266](https://github.com/ManageIQ/integration_tests/pull/9266).

[1LP][RFR] Add partial_match in BootstrapNav is_disabled method

---

src/widgetastic_patternfly/__init__.py

- __Extending__  VerticalNavigation.select() by adding kwarg handle_alert.  This will allow disabling of handle_alert call within select() when called with handle_alert=False.

[RFR] Add handle_alert kwarg to VerticalNavigation.select()

---

setup.cfg
src/widgetastic_patternfly/__init__.py

click_location can raise StopIteration, I think its a lot better to raise WidgetOperationFailed

[RFR] Raise WidgetOperationFailed instead of StopIteration in breadcrumb

---

src/widgetastic_patternfly/__init__.py

It required to validate Input.
@izapolsk @mshriver I found this specific to partternfly so I don't think we need it for `TextInput`

warning property for Input

---

src/widgetastic_patternfly/__init__.py
testing/test_flashmessages.py
testing/testing_page.html

This PR adds the ability to pass a compiled regex as the 'text' parameter for the match_messages, assert_message, and assert_success_message methods of the FlashMessages class.
For example, when testing VM retirement using the 'Time Delay from Now' option, the selected month/week/day/hour time delay values will be added to the date/time at which the page was loaded. The resulting flash message from a successful save is of the form "Retirement date set to 12/19/19 18:31 UTC". But if the time changes from one minute to the next while navigating to the Set Retirement Date page, it is impossible to predict accurately whether the flash message will display a time delay calculated from one or the other minute. Now, with a test like the following, 
```
flash_regex = re.compile(f"^Retirement date …
```

[RFR] Add regex capability to match_messages

---

src/widgetastic_patternfly/__init__.py
testing/test_bootstrap_nav.py
testing/testing_page.html

The current TEXT_DISABLED doesn't always give the correct xpath, modify it to work with all the cases.
Required for: https://github.com/ManageIQ/integration_tests/pull/9685

Modify BootstrapNav TEXT_DISABLED 

---

src/widgetastic_patternfly/__init__.py
testing/test_flashmessages.py
testing/testing_page.html

The FlashMessage class currently uses Selenium WebElements to implement its widget locator:
```
class FlashMessages(Widget):
@property
def messages(self):
result = []
msg_xpath = ('.//div[@id="flash_text_div" or '
'contains(@class, "flash_text_div")]/div[contains(@class, "alert")]')
try:
for flash_div in self.browser.elements(msg_xpath, parent=self, check_visibility=True):
result.append(FlashMessage(self, flash_div, logger=self.logger))
class FlashMessage(Widget):
def __init__(self, parent, flash_div, logger=None):
Widget.__init__(self, parent, logger=logger)
self.flash_div = flash_div
def __locator__(self):
return self.flash_div
```
This results in warnings logged to cfme.log any time a FlashMessage is read, e.g.,
```
2019-12-11 10:24:20,477 [I] [cfme] [RequestsView/flash]: Performing …
```

[RFR] Use XPath instead of Selenium WebElements for FlashMessage locator

---

src/widgetastic_patternfly/__init__.py

In the older Widget-based implementation of FlashMessages, there was silent catching of NoSuchElementException if there was no flash message block found on the page:
```
@property
def messages(self):
result = []
msg_xpath = ('.//div[@id="flash_text_div" or '
'contains(@class, "flash_text_div")]/div[contains(@class, "alert")]')
try:
for flash_div in self.browser.elements(msg_xpath, parent=self, check_visibility=True):
result.append(FlashMessage(self, flash_div, logger=self.logger))
except NoSuchElementException:
pass
return result
```
The newer View-based implementation refactored the message lookup to use a generator, and ended up dropping this exception handling. This PR restores it, in the msg_count property that gets called by the generator to look up the number of flash messages …

[RFR] Add NoSuchElementException handling back into FlashMessages.

---

testing/test_modal.py
tox.ini

The `- ` works as squelching of the nonzero exit statuses. We do not want this. Fixing that.
Also working around a problem with modal window opening right after it was closed, happening only on chrome. It will not reopen. This should be investigated.

[RFR] Do not ignore failures

---

testing/conftest.py
tox.ini

Changing the localserver to pytest_httpserver to allow running the tests on different machine than the browser is running on (a selenium container) (this allows to set host and port to listen on
with PYTEST_HTTPSERVER_HOST PYTEST_HTTPSERVER_PORT env vars).
It would probably good to merge https://github.com/RedHatQE/widgetastic.patternfly/pull/122 first to remove ignoring of the failing tests.

[RFR] Use pytest_httpserver instead of pytest-localserver

---

src/widgetastic_patternfly/__init__.py
testing/test_all_components.py

This requires https://github.com/RedHatQE/widgetastic.patternfly/pull/122 for tests to fully finish passing.
This pr mitigates the problem with `repr` discovered in CFME `integration_tests` and adding tests for such problems for all the widgets in `widgetastic.patternfly`.
Note this PR adds a test of `stringification` of (mostly) all the components defined in the `widgetastic_patternfly`. Perhaps it would be good to come-up with a way to put the tooling for this to Widgetastic itself and let all the descendant projects benefit from it somehow.
Fixes: https://github.com/ManageIQ/integration_tests/issues/10191

[RFR] Fix problem with locator in SettingsNavDropdown

---

src/widgetastic_patternfly/__init__.py
testing/test_flashmessages.py

On some applications, flash messages may dismiss themselves between WT creating the FlashMessage instance, and trying to delete it
This defaults the dismiss method to log and squash NoSuchElement and StaleElementReference exceptions.
Includes unit tests

Error handling flash dismiss

---

src/widgetastic_patternfly/__init__.py
testing/test_flashmessages.py

This PR decorates the `dismiss()` and `read()` methods in `FlashMessages` with a new method, `retry_element`. Any method decorated with `retry_element` will run up to some maximum number of tries, if `NoSuchElementException` or `StaleElementReferenceException` are raised. This is similar to the `retry_stale_element` method in https://github.com/RedHatQE/widgetastic.core/blob/cf0fe853dee3b41839fdecf00a0e5a53660109eb/src/widgetastic/utils.py#L682 , which only checks for the latter exception.
This type of exception handling is needed because individual notifications may auto-dismiss after a couple seconds, and if all notifications auto-dismiss, then the notification list element (`FlashMessages.ROOT`) may itself disappear, leading to exceptions if `read()` or `dismiss()` are running at that …

Wrap FlashMessages methods with new retry_element decorator

---

src/widgetastic_patternfly/__init__.py
testing/test_flashmessages.py
testing/testing_page.html

This PR adds the argument `ignore_messages` to `FlashMessages.assert_no_error()`. This allows the user to pass a list of message text values that should be ignored when checking for all error messages, and an `AssertionError` will not be raised if there are no other error messages.

Add ignore_messages option to assert_no_error

---

src/widgetastic_patternfly/__init__.py

Fixed #125
```
testing/test_date_picker.py .                                                          [100%]
====================================== warnings summary ======================================
testing/test_data_visualization.py:51
/home/okhatavk/Learning/widgetastic.patternfly/testing/test_data_visualization.py:51: PytestCollectionWarning: cannot collect test class 'TestDataVisualization' because it has a __init__ constructor (from: testing/test_data_visualization.py)
class TestDataVisualization(View):
-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================== 1 passed, 99 deselected, 1 warning in 76.34s (0:01:16) ===================
```

adding separate ROOT to resolve #125 issue
